### ISSUE TITLE
Typo in readme at config['elasticmail']

### ISSUE THREAD

**Issue by ObamaBinLaden1** [dena-a/laravel-elastic-email#2]
There is typo in readme config . It should be `elastic_email` rather than `elasticemail` as required by `Dena\LaravelElasticEmail\TransportManager`.
```
'elasticemail' => [
	'key' => env('ELASTIC_KEY'),
	'account' => env('ELASTIC_ACCOUNT')
]
```

**Comment by bqevin** [comment]
Did a PR with README update on same around June. Hopeful he will accept someday.
